spring:
  profiles:
    active:
     - dev
---
spring:
   profiles: dev
   application:
      name: microservicecloud-config-ldf-dev
      
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-ldf-test