---
server:
  port: 8201
spring:
  profile: dev
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
      
---

server:
  port: 8202
spring:
  profile: test
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
